name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: |
        yarn install
        make dist/assets
    - name: Build APK
      run: cd android && ./gradlew assembleRelease
  
  build_ios: 
    runs-on: macOS-10.14
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x          
      - name: Install packages
        run: |
          yarn install
          make dist/assets
      - name: Archive & Build IPA
        run: |
          cd ios
          xcodebuild -workspace Mattermost.xcworkspace -scheme Release clean archive -configuration release -sdk iphoneos -archivePath SwazmCommunity.xcarchive
          xcodebuild -exportArchive -archivePath  SwazmCommunity.xcarchive -exportPath  SwazmCommunity.ipa
